# Generated by Django 2.2.5 on 2021-09-15 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userofferlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(default='success', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='pevcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('User_Cardnumber', models.CharField(max_length=255)),
                ('User_Card_status', models.BooleanField(default=False)),
                ('User_Offerlist', models.ManyToManyField(to='Data_app.Userofferlist')),
            ],
        ),
    ]
