# Generated by Django 2.2.5 on 2021-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userofferlist',
            name='offer_parcent',
            field=models.CharField(default='10%', max_length=255),
        ),
        migrations.AlterField(
            model_name='userofferlist',
            name='offer',
            field=models.CharField(max_length=100),
        ),
    ]
