# Generated by Django 2.2.5 on 2021-09-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0002_auto_20210915_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enamesd', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='e_overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_timehour', models.DateField()),
                ('over_hour_in', models.TimeField()),
                ('over_hour_out', models.TimeField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('e_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Data_app.ename')),
            ],
        ),
    ]
