# Generated by Django 2.2.5 on 2021-09-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0003_e_overtime_ename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_overtime',
            name='over_hour_out',
            field=models.TimeField(blank=True),
        ),
    ]
